// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClHYBEeN-92NWic9MN6449Z06ZUCAkQCM',
    appId: '1:512909715569:web:ab611f7bb7c48055c453d0',
    messagingSenderId: '512909715569',
    projectId: 'smth-16c3c',
    authDomain: 'smth-16c3c.firebaseapp.com',
    storageBucket: 'smth-16c3c.firebasestorage.app',
    measurementId: 'G-HGL89FNW0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2h8B0Zv07Qa0TXOPC6_30V2Y91nzyd20',
    appId: '1:512909715569:android:4c00baa5f7eceffcc453d0',
    messagingSenderId: '512909715569',
    projectId: 'smth-16c3c',
    storageBucket: 'smth-16c3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjX_rQalqOHkmNGGFxDE7tPurr1TUulbA',
    appId: '1:512909715569:ios:506e85839e91058bc453d0',
    messagingSenderId: '512909715569',
    projectId: 'smth-16c3c',
    storageBucket: 'smth-16c3c.firebasestorage.app',
    iosBundleId: 'com.celeste.app',
  );
}
